name: Coletar Cotações Diariamente

on:
  schedule:
    - cron: '0 10 * * *'  # 🕙 roda todo dia às 10:00 UTC (~07:00 no Brasil)
  workflow_dispatch:      # permite execução manual no GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar o script de coleta
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python coletor_cotacoes.py
